export enum AdpType{
    STANDARD = "STANDARD",
    HALF_PPR = "HALF_PPR",
    PPR = "PPR",
    TWO_QB = "TWO_QB",
    DYNASTY_STANDARD = "DYNASTY_STANDARD",
    DYNASTY_HALF_PPR = "DYNASTY_HALF_PPR",
    DYNASTY_PPR = "DYNASTY_PPR",
    DYNASTY_2_QB = "DYNASTY_2_QB"
}